# Generated by Django 5.2.6 on 2025-09-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pageid',
        ),
    ]
