# Generated by Django 5.2.6 on 2025-09-10 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patient_pageid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmetrics',
            name='concentration',
        ),
        migrations.RemoveField(
            model_name='patientmetrics',
            name='duration_30_m',
        ),
        migrations.AddField(
            model_name='patientmetrics',
            name='results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientmetrics',
            name='height_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientmetrics',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='patientmetrics',
            name='weight_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
