# Generated by Django 5.2.6 on 2025-09-10 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_remove_patientmetrics_concentration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmetrics',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='patient.patient'),
        ),
    ]
